version: '3.8'
services:
  dev-db:
    image: mysql:8
    ports:
      - 3308:3306
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: nest
    networks:
      - freecodecamp
  test-db:
    image: mysql:8
    ports:
      - 3309:3306
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: